dictionary/dict/urls.py
from django.urls import path
from . import views

app_name = "dict"

urlpatterns = [
    path('', views.main, name='main'),
    path('searched/', views.search, name='search'),
    path('item/<int:pk>/', views.index, name='item'),
    path('item/<int:pk>/delete/<int:dk>/', views.item_delete, name='delete2'),
]

dictionary/dictionary/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dict.urls'))
]

dictionary/dict/models.py
from django.db import models


# class Recipe(models.Model):
#         name = models.CharField(max_length=100)
#         country = models.CharField(max_length=100)
#         ingredient = models.TextField()
#
#         def __str__(self):
#                 return self.name

class Recipe(models.Model):
    object = models.Manager()
    word = models.TextField()
    sense_no = models.TextField()
    primary_key = models.TextField()

dictionary/dict/forms.py
from django import forms


class SearchForm(forms.Form):
    search_word = forms.CharField(label='kw')

dictionary/dict/views.py
from django.shortcuts import render, redirect
from elasticsearch import Elasticsearch
from django.core.paginator import Paginator
from .models import Recipe

'''
원어/ 언어 0
활용/ 발음 0
준말/ 발음 0
용례  0
관련 어휘/ 유형 0
대역어/ 언어 0
속담/뜻풀이/유형 0
'''

es = Elasticsearch(["http://127.0.0.1:9200"])


def get(q):
    if q == "":
        return {}
    query = {
        'match': {
            'word': q
        }
    }
    search_result = es.search(index="word", query=query)
    total = search_result['hits']['total']['value']
    if total == 0:
        return {}
    page = int(total / 10) + 1
    context = []
    for i in range(1, page + 1):
        search_result = es.search(index="word", from_=(i - 1) * 10, query=query)
        for j in range(len(search_result['hits']['hits'])):
            context.append(search_result['hits']['hits'][j]['_source'])
    return context


def search(request):
    if 'delete' in request.get_full_path():
        url = search_delete(request)
        return redirect(url)
    if 'kw' in request.GET:
        query = request.GET.get('kw')
        page = request.GET.get('page')  # 페이지
        context = get(query)
        records = Recipe.object.all().order_by('-id')
        if len(context) == 0:
            return render(request, 'dict//searched.html', {'kw': query, 'records': records})
        paginator = Paginator(context, 10)  # 페이지당 10개씩 보여주기
        page_obj = paginator.get_page(page)
        return render(request, 'dict//searched.html', {'context': page_obj, 'kw': query, 'records': records})
    else:
        return render(request, 'dict//searched.html')


def main(request):
    return render(request, 'dict//base.html')


def get_result(result, string, separator):
    if result[string] is not None:
        return result[string].split(separator)
    return


def get_pro_result(result, string):
    value = []
    if result[string] is not None:
        value = result[string].split('], ')
    for i in range(len(value) - 1):
        value[i] = value[i] + "]"
    return value


def item_delete(request, pk, dk):
    Recipe.object.get(primary_key=dk).delete()
    return redirect('../../')


def search_delete(request):
    idx_pk = request.get_full_path().rindex('/')
    dk = request.get_full_path()[idx_pk + 1:]
    idx_de = request.get_full_path().rindex('delete')
    url = request.get_full_path()[:idx_de - 1]
    Recipe.object.get(primary_key=dk).delete()
    return url


def index(request, pk):
    query = {
        'match': {
            'pk': pk
        }
    }
    search_result = es.search(index="word", query=query)
    search_result = search_result['hits']['hits'][0]['_source']

    try:
        Recipe.object.filter(primary_key=pk).delete()
    except:
        print("예외")

    q = Recipe(
        word=search_result['word'],
        sense_no=search_result['sense_no'],
        primary_key=pk
    )
    q.save()

    records = Recipe.object.all().order_by('-id')
    example = get_result(search_result, "example", ',  ')
    if example is not None:
        last = example[len(example) - 1]
        example[len(example) - 1] = last[0:len(last) - 1]
        for i in range(len(example)):
            example[i] = example[i].replace("}", "").replace("{", "")

    conjugation = get_result(search_result, "conjugation", ', ')
    conjugation_pro = get_pro_result(search_result, "conjugation_pro")
    conju_dic = {}
    if conjugation is not None and conjugation_pro is not None:
        conju_dic = {name: value for name, value in zip(conjugation, conjugation_pro)}

    abbreviation = get_result(search_result, "abbreviation", ', ')
    abbreviation_pro = get_pro_result(search_result, "abbreviation_pro")
    abbre_dic = {}
    if abbreviation is not None and abbreviation_pro is not None:
        abbre_dic = {name: value for name, value in zip(abbreviation, abbreviation_pro)}

    relation_word = get_result(search_result, "relation_word", ', ')
    relation_type = get_result(search_result, "relation_type", ', ')
    relation_dic = {}
    word_list = []
    if relation_word is not None:
        for i in range(len(relation_word)):
            if i != 0 and relation_type[i] != relation_type[i - 1]:
                relation_dic[relation_type[i - 1]] = word_list
                word_list = []
            word_list.append(relation_word[i])
        relation_dic[relation_type[len(relation_type) - 1]] = word_list

    proverb = get_result(search_result, 'proverb', '   ')
    pro_defi = get_result(search_result, 'pro_defi', '   ')
    pro_type = get_result(search_result, 'pro_type', '   ')
    proverb_dict = {}
    if proverb is not None:
        for i in range(len(proverb)):
            proverb_dict[proverb[i]] = {pro_defi[i]: pro_type[i]}

    original_language = get_result(search_result, 'original_language', ', ')
    language_type = get_result(search_result, 'language_type', ', ')
    language_dict = {}
    if original_language is not None:
        language_dict = {name: value for name, value in zip(original_language, language_type)}

    return render(request, 'dict//item.html', {'result': search_result, 'example': example,
                                               'conjugation': conju_dic, 'abbreviation': abbre_dic,
                                               'relation': relation_dic, 'proverb': proverb_dict,
                                               'language': language_dict, 'records': records})

dictionary/dict/templates/dict/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Document</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
</head>
<body>
<div style="display:flex; width:90%">
    <div style="display:flex; margin:auto">
    <header style="margin:20px;">
         <body link = "0000ff" vlink="0000ff">
            <a href = "{% url 'dict:main' %}">
                <h1>국어사전</h1>
            </a>
        </body>
    </header>
    <form class="form" action="{% url 'dict:search'%}" method="get" style = 'display:flex; margin:auto' >
        <input class="form-control input-lg" type="search" placeholder="Search" name="kw" style="width: 200%; height:35px; border-radius:10px">
        <button class="btn btn-outline-info" type="submit" style="height:35px; border-radius:10px; margin-left:10px" > Search</button>
    </form>
    </div>
</div>
    <div class = 'container' style="margin:auto">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>

dictionary/dict/templates/dict/item.html
{% extends "dict//base.html" %}
{% block content %}
<div style="display:flex">
<div class="container" style="width:70%;margin-auto;margin-right:0px;padding:0px; border-right:solid 1px gray" >
    <!-- 검색결과 목록 start -->
    <div class="search_result">
        <div class = 'col' style = 'display: flex; border-top:2px solid black; ' >
            <div class = "row-md-1">
                <h1 style = 'margin:3px; margin-right:10px'>{{result.word}}</h1>
            </div>
            <div class = 'row-md-1'>
                <div class="col">
                    <div class = 'row-md-1'>
                        <h4 style = 'margin-top:3px;margin-bottom: 0px;'>「{{result.word_type}}」</h4>
                    </div>
                    <div class = 'row-md-1' style='display: flex'>
                        {% for key,value in language.items %}
                        {% if key != '/' %}
                        <p style="margin:auto;">{{key}}({{value}})  </p>
                        {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>

        <hr style="margin:5px">
        <div class = 'container' style = 'display: flex; padding:0px'>
            <!-- 발음 -->
            {% if result.pronunciation != None %}
            <div style = 'margin-right: 15px'>
                <dt style="text-align:center">발음</dt>
                <dt style="text-align:center;font-weight : normal;">{{result.pronunciation}}</dt>
            </div>
            {% endif %}
            <!-- 품사 -->
            <div style = 'margin-right: 15px'>
                <dt style="text-align:center">품사</dt>
                <dt style="text-align:center;font-weight : normal;">「{{result.pos}}」</dt>
            </div>
            <!-- 범주 -->
            <div style = 'margin-right: 15px'>
                <dt style="text-align:center">범주</dt>
                <dt style="text-align:center;font-weight : normal;">「{{result.type}}」</dt>
            </div>
            <!-- 전문 분야 -->
            {% if result.cat != None %}
            <div style = 'margin-right: 15px'>
                <dt style="text-align:center">전문 분야</dt>
                <dt style="text-align:center;font-weight : normal;">{{result.cat}}</dt>
            </div>
            {% endif %}
            <!-- 대역어 -->
            {% if result.translation != None %}
            <div style = 'margin-right: 15px'>
                <dt style="text-align:center">대역어</dt>
                <dt style="text-align:center;font-weight : normal;">{{result.translation}}({{result.translation_language}})</dt>
            </div>
            {% endif %}
            <!-- 이형태 -->
            {% if result.origin != None %}
            <div style = 'margin-right: 15px'>
                <dt style="text-align:center">이형태</dt>
                <dt style="text-align:center;font-weight : normal;">{{result.origin}}</dt>
            </div>
            {% endif %}
            <!-- 어원 -->
            {% if result.allomorph != None %}
            <div style = 'margin-right: 15px'>
                <dt style="text-align:center">어원</dt>
                <dt style="text-align:center;font-weight : normal;">{{result.allomorph}}</dt>
            </div>
            {% endif %}
        </div>
        <hr style="margin:5px">
        <!-- 기본목록 start -->
        <div class="search_view_list group mt30">
            <!-- 뜻풀이 -->
            <span style= "color:#B0ADAD">「{{result.sense_no}}」</span> <span>{{result.definition}}</span>
            <!-- 용례 -->

            {% if example %}
            <hr style="margin:5px;">
            <!-- 용례 - 기본 -->
            {% for word in example %}
            {% if forloop.counter0 < 5 %}
            <ul style="marker-offset:2em; padding-left:25px; margin-bottom:3px">
                <li>{{word}}</li>
            </ul>
            {% endif %}
            {% endfor %}

            {% if example|length >= 5 %}
            <div class="collapse" id="collapseExample">
                <div>
                    {% for word in example %}
                    {% if forloop.counter0 >= 5 %}
                    <ul style="marker-offset:2em; padding-left:25px; margin-bottom:3px">
                        <li>{{word}}</li>
                    </ul>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
            <div style="text-align:right">
                <a data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample" style="text-align:right;">
                    더보기
                </a>
            </div>
            {% endif %}
            {% endif %}

            <!-- 활용 -->
            {% if conjugation %}
            <dl>
                <dt style="margin-left:5px"><strong>활용</strong></dt>
                {% for key, value in conjugation.items %}
                <dd style="margin-left:10px; margin-bottom:4px">
                    {{key}} : {{value}}
                </dd>
                {% endfor %}
            </dl>
            {% endif %}

            <!-- 준말 -->
            {% if abbreviation %}
            <dl>
                <dt><strong>준말</strong></dt>
                {% for key, value in abbreviation.items %}
                <dd>
                    {{key}} : {{value}}
                </dd>
                {% endfor %}
            </dl>
            {% endif %}

            {% if result.grammar != None %}
            <dl>
                <dt><strong>문법</strong></dt>
                <dd>
                    {{result.grammar}}
                </dd>
            </dl>
            {% endif %}

        </div>
        <!--// 기본목록 end -->
        <!-- 관련 어휘 -->
        {% if relation %}
        <hr style="margin:5px">
        <div class="search_view_list group">
            <h4 style="margin-bottom: 5"><strong>관련 어휘</strong></h4>
            <div class="search_meaning ">
                {% for key, value in relation.items %}
                <dl style="margin-left:5px;margin-top:5px; display:flex">
                    <div style="margin-right:3px;">
                        <dt style="margin: 0; width: 70px">{{key}}</dt>
                    </div>
                    <dd>{{value}}</dd>
                </dl>
                {% endfor %}
            </div>
        </div>
        {% endif %}
        <!-- 대역어 -->
    </div>


    <!-- 관용구, 속담 -->
    {% if proverb  %}
    <hr style="margin:5px">
    <div class="search_view_list">
       <div class="search_proverb">
            <details open>
                <summary style="font-size:120%">관용구·속담(<strong>{{proverb|length}}</strong>)</summary>
                {% for key, value in proverb.items %}
                {% for key2, value2 in value.items %}
                <dl style="margin-top: 5px">
                    <dt>
                        <span class="btn btn-dark disabled btn-sm">{{value2}}  </span><strong>  {{key}}</strong>
                    </dt>
                    <dd>{{key2}}</dd>
                </dl>
                {% endfor %}
                {% endfor %}
            </details>
        </div>
    </div>
    {% endif %}
</div>
    <div style="position:sticky; top:80px;height: 100px;margin:auto; margin-left:0px; margin-top:0px">
    <!-- 검색한 단어 -->
       <header style="text-align:center; border: 1px solid black; border-left:0pxs">
           <h4>내가 찾은 단어</h4>
           {% for record in records %}
           <nav>
               <li  style = 'margin:5px; text-align:left'>
                    <a href = "{% url 'dict:item' record.primary_key %}" style="text-decoration:none; color:black"  >{{record.word}}{{record.sense_no}}</a>
                    <a href = "/item/{{result.pk}}/delete/{{record.primary_key}}/">x</a>
               </li>
           </nav>
           {% endfor %}
       </header>
    </div>
</div>

{% endblock %}

dictionary/dict/templates/dict/searched.html
{% extends 'dict//base.html' %}

{% block content %}
<div style="display:flex;">
    <div class = 'container' style="margin:auto;margin-right:0px;margin-top:0px;border: 1px solid red; width:70%">
        {% if context %}
            {% for word in context%}
                <div class = 'col' style = 'display: flex; margin = 0; margin-top:5px'>
                    <div class = 'row-md-1'>
                        <h1 style = 'margin-right: 10px;'><a href = "{% url 'dict:item' word.pk %}" style="vertical-align:middle; ">{{ word.word }}</a></h1>
                    </div>
                    <div class = 'row-md-1'>
                        <div class = "col">
                            <div class = "row-md-1">
                                <h6 style = 'margin-top: 7px; margin-bottom: 0'>{{ word.sense_no }}</h6>
                            </div>
                            <div class = "row-md-1">
                                {% if word.pronunciation != None %}
                                <h6 style = 'margin-bottom: 0'>{{ word.pronunciation}}</h6>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                <h5 style = 'margin: 0'>{{ word.definition}}</h5>
            {% endfor %}
        <div>
            <!-- 페이징처리 시작 -->
        <ul class = "pagination" style="justify-content:center; margin-top:15px">
            <!-- 이전페이지 -->
            {% if context.has_previous %}
                <li><a class="page-link" href="?kw={{kw}}&page={{ context.previous_page_number }}">이전</a></li>
            {% else %}
                <li><a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a></li>
            {% endif %}

            <!-- 페이지리스트 -->
            {% for page_number in context.paginator.page_range %}
            {% if page_number >= context.number|add:-5 and page_number <= context.number|add:5 %}
            {% if page_number == context.number %}
                <li class="active"><a class="page-link">{{ page_number }}</a></li>
            {% else %}
                <li><a class="page-link" href="?kw={{kw}}&page={{ page_number }}">{{ page_number }}</a></li>
            {% endif %}
            {% endif %}
            {% endfor %}

            <!-- 다음페이지 -->
            {% if context.has_next %}
                <li><a class="page-link" href="?kw={{kw}}&page={{ context.next_page_number }}">다음</a></li>
            {% else %}
                <li><a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a></li>
            {% endif %}
        </ul>
        <!-- 페이징처리 끝 -->
        </div>
        {% else %}<!-- 검색 결과가 없는 경우-->
        <div style="margin:0px">
            <b><i>'{{kw}}'은(는) 등록되어 있지 않습니다.</i></b>
        </div>
        {% endif %}
    </div>
    <div style="position:sticky; top:80px;height: 100px;margin:auto; margin-left:0px; margin-top:0px">
    <!-- 검색한 단어 -->
       <header style="text-align:center; border: 1px solid black;">
           <h4>내가 찾은 단어</h4>
           {% for record in records %}
           <nav>
               <li  style = 'margin:5px; text-align:left'>
                   <a href = "{% url 'dict:item' record.primary_key %}" style="text-decoration:none; color:black"  >{{record.word}}{{record.sense_no}}</a>
                   <a href = "/searched/?kw={{kw}}/delete/{{record.primary_key}}">x</a>
               </li>
           </nav>
           {% endfor %}
       </header>
        </div>
</div>
{% endblock %}